github:
  public: true
  is_project_page: false
highlighter: rouge
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
paginate: 10
theme: jekyll-theme-tactile
sass:
  sass_dir: _sass
title: DillonAd
links:
  - site:
      url: https://github.com/DillonAd
      icon: fa-github
      description: GitHub
      a11y_label: GitHub
  - site:
      url: https://hachyderm.io/@DillonAd
      icon: fa-brands fa-mastodon
      description: Mastadon
      a11y_label: Mastadom
  - site:
      url: https://stackoverflow.com/users/7359614/dillon-adams
      icon: fa-stack-overflow
      description: StackOverflow
      a11y_label: StackOverflow
  - site:
      url: https://www.linkedin.com/in/dillon-adams
      icon: fa-linkedin
      description: LinkedIn
      a11y_label: LinkedIn
  - site:
      url: https://dev.to/dillonad
      icon: fa-dev
      description: Dev
      a11y_label: Dev.to
navigation:
  - page:
      name: Blog
      link: /
  - page:
      name: About
      link: /AboutMe
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dillon Adams"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"