name: Publish

on: 
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Get Changed Files
      uses: lots0logs/gh-action-get-changed-files@1.0.0

    - name: Publish articles 
      uses: tylerauerbeck/publish-to-dev.to-action@master
      env:
        DEV_TO_TOKEN: ${{ secrets.DEV_TO_TOKEN }}
        PR_LIST_FILE: ${HOME}/files.json
